; This file contains the period values for every note that the NES can
; reproduce.
;
; Each period value was calculated with the following forumula:
;
; period = CPU / (f * 16) - 1
;
; where:
;   CPU is the CPU speed in Hz (1790000 for NTSC)
;   f is the note frecuency in Hz

A0  = $FE3
Bb0 = $EFF
B0  = $E27

C1  = $D5C
Db1 = $C9C
D1  = $BE7
Eb1 = $B3C
E1  = $A9A
F1  = $A02
Gb1 = $972
G1  = $8EA
Ab1 = $86A
A1  = $7F1
Bb1 = $77F
B1  = $713

C2  = $6AD
Db2 = $64D
D2  = $5F3
Eb2 = $59D
E2  = $54D
F2  = $500
Gb2 = $4B8
G2  = $475
Ab2 = $435
A2  = $3F8
Bb2 = $3BF
B2  = $389

C3  = $356
Db3 = $326
D3  = $2F9
Eb3 = $2CE
E3  = $2A6
F3  = $280
Gb3 = $25C
G3  = $23A
Ab3 = $21A
A3  = $1FC
Bb3 = $1DF
B3  = $1C4

C4  = $1AB
Db4 = $193
D4  = $17C
Eb4 = $167
E4  = $152
F4  = $13F
Gb4 = $12D
G4  = $11C
Ab4 = $10C
A4  = $FD
Bb4 = $EF
B4  = $E2

C5  = $D5
Db5 = $C9
D5  = $BD
Eb5 = $B3
E5  = $A9
F5  = $9F
Gb5 = $96
G5  = $8E
Ab5 = $86
A5  = $7E
Bb5 = $77
B5  = $70

C6  = $6A
Db6 = $64
D6  = $5E
Eb6 = $59
E6  = $54
F6  = $4F
Gb6 = $4B
G6  = $46
Ab6 = $42
A6  = $3F
Bb6 = $3B
B6  = $38

C7  = $34
Db7 = $31
D7  = $2F
Eb7 = $2C
E7  = $29
F7  = $27
Gb7 = $25
G7  = $23
Ab7 = $21
A7  = $1F
Bb7 = $1D
B7  = $1B

C8  = $1A
